### ISSUE TITLE
Logos in Open Studs too large

### ISSUE THREAD

**Issue by Copperplate** [TobyLobster/ImportLDraw#18]
Hi Toby, just discovered your addon yesterday, and I have to say it is incredible! Excellent work in expanding, building upon, and re-writing an already great system. I am very impressed, and really like your implementation of the bevel modifier.

It's too bad that many High Res Primitives in LDraw often are modeled with disconnected vertices or have an uneven fill carried over from the Standard Res Primitives (check out the ends of Technic pin 6558 to see what I mean). This of course is because the parts were probably never intended to be used with fancy things like bevel modifiers which grab these loose vertices and can cause all kinds of distortion. Not sure that there's really anything the add-on could do to fix that though... :-)

![6558 dat](https://user-images.githubusercontent.com/16230743/38460248-9b7f08ec-3a7b-11e8-99c8-af2b2f744389.PNG)

One thing I've come across that probably could be fixed is that logos inside open studs unfortunately come out too large (they are the same size as on closed studs, which causes the logo to be cut off). I've found that one has to manually select these logos and shrink them by 0.76 to keep them within the diameter of the open stud. You can see this in parts like 3794b or 18975.

Anyway, thank you again so much for your excellent work in developing this extremely helpful addon!

-Adam

![99781 dat](https://user-images.githubusercontent.com/16230743/38460259-d319ca44-3a7b-11e8-83ae-208c69efad21.PNG)

**Comment by BertVanRaemdonck** [comment]
As far as I can see, the topologyproblem is not something that can be fixed with the importer right now, as it basically would require to write could that could automatically generate a clean mesh... I actually avoid using the high resolution primitives altogether and instead use a subdivision surface modifier in blender itself in order to get nice smooth renders. That also saves on import time. I think you can do it for all parts at once by linking the modifiers together as they are basically the same for each part, but the problem then is that you probably generate a lot of excessive geometry. Of course, de subdivision surface doesn't work everywhere, like it doesn't fix the notches in the Technic pins, so for that you need to do some manual remodelling I'm afraid, which isn't too bad as the geometry is linked between the different parts.

The  only solution I see is to create a library of remodelled parts which are better for rendering, of course only for those parts which commonly give problems. It could be a group effort and could come packed with the importer, like the stud files already are.

Speaking of the stud files, the issue with the oversized logos is an easy fix, not even worth creating a pull request over. You can also easily fix it yourself and doesn't even require you to go to the source code of the importer. What you have to do is to go to the ImportLDraw folder and open the "studs" subfolder. Then open the "stud2-logo3.dat" to "stud2-logo5.dat" files in a text editor and each time change the last line to "1 16 0 0 0 0.7 0 0 0 0.7 0 0 0 0.7", followed by the logo name that's already there. If you want to use 0.76 insted of 0.7, of course that's fine as well.

That fixes your problem, but I wonder why this hasn't been done in the original code, as for the stud6a-logo files, the factor of 0.7 _is_ included. So was this intentional or just an oversight? Anyway, it's an easy fix for those who want it. I hope this helped!

**Comment by Copperplate** [comment]
Hi Bert, thank you so much for your detailed and helpful reply! I will have to try that adjustment to the logo files out the next time I need to import LDraw files. As for the topology issues, now that we have the [new bevel shader in Blender](https://youtu.be/aiB_mpL2C-g), I wonder if this will help mitigate the tearing that happens on these parts when a real bevel modifier is used. :-)

**Comment by TobyLobster** [comment]
The stud size issue is now fixed in the latest release, thanks.

**Comment by Copperplate** [comment]
Hey, that's great to hear! Thank you, Toby!!
