### ISSUE TITLE
Is it possible to import custom parts?

### ISSUE THREAD

**Issue by Kinc4id** [TobyLobster/ImportLDraw#75]
I have a model with some parts I created in PartDesigner. Just standard parts with decals. When I import this model everything works fine, but these parts are empty. Is there a way to import these parts or should I use standard parts and apply the decal in blender?

**Comment by TobyLobster** [comment]
Sorry, I've not used PartDesigner, so don't know what it exports. 

My importer expects custom parts to be present as .dat files. If the decals are textures, then you may have more luck importing standard parts and applying the decal in Blender. This is because LDraw uses geometry to create patterns and stickers rather than textures.
